# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R8l_53WLFINHiedvaDwdYPo52ynV9EfY
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect('student_management.db')
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE Students (
    student_id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_name TEXT,
    gender TEXT,
    age INTEGER,
    department TEXT
)
""")

cursor.execute("""
CREATE TABLE Courses (
    course_id INTEGER PRIMARY KEY AUTOINCREMENT,
    course_name TEXT,
    credits INTEGER
)
""")

cursor.execute("""
CREATE TABLE Marks (
    mark_id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_id INTEGER,
    course_id INTEGER,
    marks INTEGER,
    exam_date TEXT
)
""")

cursor.executemany("""
INSERT INTO Students
(student_name, gender, age, department)
VALUES (?, ?, ?, ?)
""", [
    ('Rahul Sharma', 'Male', 20, 'Computer Science'),
    ('Priya Reddy', 'Female', 21, 'Electronics'),
    ('Arjun Kumar', 'Male', 22, 'Mechanical'),
    ('Sneha Patel', 'Female', 20, 'Computer Science'),
    ('Vikram Singh', 'Male', 23, 'Civil')
])

cursor.executemany("""
INSERT INTO Courses
(course_name, credits)
VALUES (?, ?)
""", [
    ('Database Management System', 4),
    ('Data Structures', 3),
    ('Operating Systems', 4),
    ('Mathematics', 3)
])

cursor.executemany("""
INSERT INTO Marks
(student_id, course_id, marks, exam_date)
VALUES (?, ?, ?, ?)
""", [
    (1, 1, 88, '2026-01-10'),
    (1, 2, 91, '2026-01-12'),
    (2, 1, 76, '2026-01-10'),
    (2, 3, 82, '2026-01-14'),
    (3, 2, 69, '2026-01-12'),
    (3, 4, 73, '2026-01-16'),
    (4, 1, 95, '2026-01-10'),
    (4, 3, 89, '2026-01-14'),
    (5, 4, 64, '2026-01-16')
])

conn.commit()

students = pd.read_sql_query(
    "SELECT * FROM Students",
    conn
)

students

query1 = """
SELECT
    s.student_name,
    AVG(m.marks) AS average_marks
FROM Students s
JOIN Marks m
ON s.student_id = m.student_id
GROUP BY s.student_name
"""

result1 = pd.read_sql_query(query1, conn)

result1

query2 = """
SELECT
    s.student_name,
    AVG(m.marks) AS average_marks
FROM Students s
JOIN Marks m
ON s.student_id = m.student_id
GROUP BY s.student_name
ORDER BY average_marks DESC
LIMIT 1
"""

result2 = pd.read_sql_query(query2, conn)

result2

query3 = """
SELECT
    c.course_name,
    AVG(m.marks) AS average_marks
FROM Courses c
JOIN Marks m
ON c.course_id = m.course_id
GROUP BY c.course_name
"""

result3 = pd.read_sql_query(query3, conn)

result3

query4 = """
SELECT
    s.student_name,
    c.course_name,
    m.marks
FROM Students s
JOIN Marks m
ON s.student_id = m.student_id
JOIN Courses c
ON c.course_id = m.course_id
WHERE m.marks > 80
"""

result4 = pd.read_sql_query(query4, conn)

result4

query5 = """
SELECT
    s.student_name,
    SUM(m.marks) AS total_marks
FROM Students s
JOIN Marks m
ON s.student_id = m.student_id
GROUP BY s.student_name
"""

result5 = pd.read_sql_query(query5, conn)

result5

query6 = """
SELECT
    s.student_name,
    AVG(m.marks) AS average_marks
FROM Students s
JOIN Marks m
ON s.student_id = m.student_id
GROUP BY s.student_name
ORDER BY average_marks DESC
"""

result6 = pd.read_sql_query(query6, conn)

result6

conn.close()